// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

/// <reference types='node' />
// Required to access Node globals in this file

import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
